# Copyright (c) 2026, NVIDIA CORPORATION.  All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Prompt-group batch selection strategies for SingleController metadata."""

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, Protocol

from nemo_rl.data_plane import KVBatchMeta


@dataclass(frozen=True)
class PromptGroup:
    """Indices and scheduling metadata for one prompt group."""

    group_id: str
    indices: list[int]
    weight_version: int | None
    committed: bool
    expected_num_samples: int

    @property
    def is_complete(self) -> bool:
        return len(self.indices) == self.expected_num_samples


class BatchSelectionStrategy(Protocol):
    """Select sample indices from claimed DataPlane metadata."""

    def select_indices(
        self,
        meta: KVBatchMeta,
        *,
        trainer_version: int,
        min_prompt_groups: int,
        generations_per_prompt: int,
    ) -> Optional[list[int]]:
        """Return selected sample indices, or None if no full batch is available."""

    def evictable_indices(
        self,
        meta: KVBatchMeta,
        *,
        trainer_version: int,
        generations_per_prompt: int,
    ) -> list[int]:
        """Return sample indices that are no longer eligible."""


@dataclass
class StrictOnPolicySelection:
    """Select only complete prompt groups generated by the trainer version."""

    def select_indices(
        self,
        meta: KVBatchMeta,
        *,
        trainer_version: int,
        min_prompt_groups: int,
        generations_per_prompt: int,
    ) -> Optional[list[int]]:
        groups = [
            group
            for group in _prompt_groups(meta, generations_per_prompt)
            if group.committed
            and group.is_complete
            and group.weight_version == trainer_version
        ]
        if len(groups) < min_prompt_groups:
            return None
        return _flatten_group_indices(groups[:min_prompt_groups])

    def evictable_indices(
        self,
        meta: KVBatchMeta,
        *,
        trainer_version: int,
        generations_per_prompt: int,
    ) -> list[int]:
        groups = [
            group
            for group in _prompt_groups(meta, generations_per_prompt)
            if group.weight_version is not None
            and group.weight_version < trainer_version
            and group.is_complete
        ]
        return _flatten_group_indices(groups)


class StrictOnPolicyBatchSampler(StrictOnPolicySelection):
    """Strict full-prompt-group sampler for on-policy overlap experiments."""


@dataclass
class StalenessWindowSelection:
    """Select complete prompt groups inside a version staleness window."""

    max_staleness_versions: int

    def select_indices(
        self,
        meta: KVBatchMeta,
        *,
        trainer_version: int,
        min_prompt_groups: int,
        generations_per_prompt: int,
    ) -> Optional[list[int]]:
        eligible: list[tuple[int, int, PromptGroup]] = []
        for group in _prompt_groups(meta, generations_per_prompt):
            if not group.committed or not group.is_complete:
                continue
            if group.weight_version is None or group.weight_version > trainer_version:
                continue
            lag = trainer_version - group.weight_version
            if lag > self.max_staleness_versions:
                continue
            eligible.append((lag, group.indices[0], group))

        if len(eligible) < min_prompt_groups:
            return None

        eligible.sort(key=lambda item: (item[0], item[1]))
        groups = [item[2] for item in eligible[:min_prompt_groups]]
        return _flatten_group_indices(groups)

    def evictable_indices(
        self,
        meta: KVBatchMeta,
        *,
        trainer_version: int,
        generations_per_prompt: int,
    ) -> list[int]:
        groups = []
        for group in _prompt_groups(meta, generations_per_prompt):
            if group.weight_version is None or not group.is_complete:
                continue
            lag = trainer_version - group.weight_version
            if lag > self.max_staleness_versions:
                groups.append(group)
        return _flatten_group_indices(groups)


class StalenessSampler(StalenessWindowSelection):
    """Backward-compatible name for the staleness-window selector."""


def count_prompt_groups(
    meta: KVBatchMeta,
    *,
    generations_per_prompt: int,
) -> int:
    """Count complete prompt groups represented by ``meta``."""
    return sum(
        1
        for group in _prompt_groups(meta, generations_per_prompt)
        if group.is_complete
    )


def _prompt_groups(
    meta: KVBatchMeta,
    generations_per_prompt: int,
) -> list[PromptGroup]:
    tags = meta.tags or [{} for _ in meta.sample_ids]
    grouped: dict[str, list[int]] = {}
    first_tag: dict[str, dict] = {}

    for idx, sample_id in enumerate(meta.sample_ids):
        tag = tags[idx] if idx < len(tags) else {}
        group_id = str(tag.get("group_id") or _group_id_from_sample_id(sample_id))
        grouped.setdefault(group_id, []).append(idx)
        first_tag.setdefault(group_id, tag)

    groups: list[PromptGroup] = []
    for group_id, indices in grouped.items():
        tag = first_tag[group_id]
        expected = _as_int(
            tag.get(
                "expected_num_samples",
                tag.get(
                    "expected_num_keys",
                    tag.get("generations_per_prompt", generations_per_prompt),
                ),
            )
        )
        groups.append(
            PromptGroup(
                group_id=group_id,
                indices=indices,
                weight_version=_weight_version(tag),
                committed=_as_bool(tag.get("committed", True)),
                expected_num_samples=expected or generations_per_prompt,
            )
        )
    groups.sort(key=lambda group: group.indices[0])
    return groups


def _flatten_group_indices(groups: list[PromptGroup]) -> list[int]:
    return [idx for group in groups for idx in group.indices]


def _group_id_from_sample_id(sample_id: str) -> str:
    prefix, sep, suffix = sample_id.rpartition("_g")
    if sep and suffix.isdigit():
        return prefix
    return sample_id


def _weight_version(tag: dict) -> int | None:
    value = tag.get("weight_version", tag.get("version"))
    return _as_int(value)


def _as_int(value) -> int | None:
    if value is None:
        return None
    try:
        return int(value)
    except (TypeError, ValueError):
        return None


def _as_bool(value) -> bool:
    if isinstance(value, bool):
        return value
    if isinstance(value, str):
        return value.lower() in {"1", "true", "yes"}
    return bool(value)
